name: CI

on: 
  push:
    branches:
      - build-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Init PHP with specific version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, sqlite, gd, zip
    - name: Cache Node dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-lock-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-lock-
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-dev
    - name: Prepare
      run: |
        cp .env.example .env
        php artisan key:generate
        mkdir -p resources/views/overrides
    - name: Validate Twig templates
      run: php artisan twig:lint -v
    - name: yarn install
      run: yarn
    - name: run build.ps1 file
      shell: pwsh
      run: ./tools/build.ps1
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
    - name: Archive release
      run: zip -9 -r blessing-skin-server-${{ steps.short-sha.outputs.sha }}.zip app bootstrap config database plugins public resources/lang resources/views resources/misc/textures routes storage vendor .env.example artisan LICENSE README.md README-zh.md index.html
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: blessing-skin-server-${{ steps.short-sha.outputs.sha }}.zip
